import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext"

export const metadata = {
  title: "AbstraZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
        <Navbar />
        <div id = "root">{children}</div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
