import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "EthOnline Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div id = "root">{children}</div>
      </body>
    </html>
  );
}
